"""Generate coin_price table

Revision ID: d5d8243fe536
Revises: 0e3a452c6b19
Create Date: 2025-02-05 10:04:40.452320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d8243fe536'
down_revision: Union[str, None] = '0e3a452c6b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coin_prices_id'), 'coin_prices', ['id'], unique=False)
    op.create_index(op.f('ix_coin_prices_symbol'), 'coin_prices', ['symbol'], unique=False)
    op.drop_index('ix_coins_id', table_name='coins')
    op.drop_index('ix_coins_name', table_name='coins')
    op.drop_index('ix_coins_symbol', table_name='coins')
    op.drop_table('coins')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('trend', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('change_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='coins_pkey')
    )
    op.create_index('ix_coins_symbol', 'coins', ['symbol'], unique=True)
    op.create_index('ix_coins_name', 'coins', ['name'], unique=False)
    op.create_index('ix_coins_id', 'coins', ['id'], unique=False)
    op.drop_index(op.f('ix_coin_prices_symbol'), table_name='coin_prices')
    op.drop_index(op.f('ix_coin_prices_id'), table_name='coin_prices')
    op.drop_table('coin_prices')
    # ### end Alembic commands ###
